name: Build and Deploy
on:
  push:
    branches:
      - ucsc

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --force
      - name: Build
        run: npm run build
      - name: Archive Production Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: ssrServer
          path: |
            functions/build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ssrServer
          path: functions/build
      - name: Set Firebase Project
        uses: w9jds/firebase-action@master
        with:
          args: use ucsc
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_UCSC }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --force
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_UCSC }}
